'use client'

import { motion } from 'framer-motion'
import { Container, SectionHeading, ImageCarousel } from '@/components/ui'
import { ProfileBio } from './ProfileBio'
import { useTranslations } from '@/i18n'
import { fadeInUp } from '@/lib/motion'

// Import profile images manifest (generated by script)
import profileImages from '@/content/profileImages.json'

/**
 * Get image filenames for profile images
 * Only uses images from public/profile/
 */
function getProfileImages(): string[] {
  if (!profileImages.images || profileImages.images.length === 0) {
    return []
  }
  return profileImages.images as string[]
}

/**
 * Profile section with image carousel and bio
 * Option A: Split layout - carousel on left, bio on right
 */
export function ProfileSection() {
  const t = useTranslations('profile')
  const images = getProfileImages()

  return (
    <section id="profile" className="py-16 sm:py-20 md:py-24 lg:py-32">
      <Container size="xl">
        <SectionHeading
          title={t('title')}
          subtitle={t('subtitle')}
        />

        {/* Two-column layout: Carousel (40%) | Bio (60%) */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 lg:gap-12 items-center">
          {/* Image carousel - left side */}
          <motion.div
            className="lg:col-span-5"
            {...fadeInUp(0)}
          >
            <ImageCarousel
              images={images}
              basePath="/profile"
              alt={t('imageAlt')}
              interval={6000}
              aspectRatio="portrait"
              showProgress={true}
              showCounter={true}
              showDots={true}
              showArrows={true}
              className="max-w-md mx-auto lg:mx-0 shadow-xl"
            />
          </motion.div>

          {/* Bio content - right side */}
          <div className="lg:col-span-7">
            <ProfileBio />
          </div>
        </div>
      </Container>
    </section>
  )
}
