export { ProjectPageClient } from './ProjectPageClient'
export { ProjectCard } from './ProjectCard'
export { FeaturedProjectsSection } from './FeaturedProjectsSection'
export { RotatingThumbnail } from './components/RotatingThumbnail'
export { ProjectImageCarousel } from './components/ProjectImageCarousel'
export { useImageRotation } from './hooks/useImageRotation'
export type { Project, LocalizedProject, ProjectType } from './types'
export { getLocalizedProject, getProjectImagePaths, getProjectHeroPath } from './types'
