// This file is generated by scripts/generate-marketplace-stats.mjs.
// Do not edit manually.

export const marketplaceStats = {
  "codeXr": {
    "downloadCount": 623,
    "displayDownloads": "600+",
    "updatedAt": "2026-06-24T09:41:30.994Z",
    "sourceUrl": "https://marketplace.visualstudio.com/items?itemName=aMonteSl.code-xr"
  }
} as const

export type MarketplaceStats = typeof marketplaceStats
