// This file is generated by scripts/generate-marketplace-stats.mjs.
// Do not edit manually.

export const marketplaceStats = {
  "codeXr": {
    "downloadCount": 727,
    "displayDownloads": "700+",
    "updatedAt": "2026-08-29T13:25:10.641Z",
    "sourceUrl": "https://marketplace.visualstudio.com/items?itemName=aMonteSl.code-xr"
  }
} as const

export type MarketplaceStats = typeof marketplaceStats
